# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59e844d65685b72541f76b000fb08985cb2c680b98e0faacbabaf508450ad028a52afaeb957e5c5c3de225ec3701854f6c3a056b522890f035e08012bbad74ca

test:
  secret_key_base: 1abe0a080ba08f488d7855b668e941c8a570c0ab309aa150da5b2a2bd8a4115a4668bc960bf75fe8d75cd18162844751efb96684d46804c97ff9cbbdd5b3469e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
